project:
  type: website
  output-dir: docs
  resources:
    - dotfield.js

website:
  title: "Levi Mackay - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/levibmackay/data-science-portfolio
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer:
    border: true
    left: "Levi Mackay 2026©"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/levi-mackay-217380396

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competitions"
        file: competition.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <canvas id="dot-field" aria-hidden="true"></canvas>
        <script src="/dotfield.js"></script>



